apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - prometheus.yaml
  - grafana.yaml
  - gpu-exporter.yaml
  - grafana-dashboard-provider.yaml
configMapGenerator:
  - name: grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/Node_Exporter_Full.json
      - dashboards/Nvidia_GPU_Metrics.json
    options:
      disableNameSuffixHash: true
