apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - open-webui.yaml
  - jarvis-webui-hud.yaml
  - chat-stream.yaml
  - piper.yaml
  - piper-voice-map.yaml
  - homepage.yaml
  - jarvis-persona.yaml
  - jarvis-orchestrator.yaml
  - jarvis-orchestrator-rbac.yaml
  - jarvis-glass.yaml
  - jarvis-noc.yaml
